### ISSUE TITLE
appsettings.json Naming Conventions.

### ISSUE THREAD

**Issue by BoozyDoo** [NCCOpenSource/GoVote#1]
Hi 

Could you please confirm I have the correct idea about some of the parameters in your appsettings.json file.

Thanks in advance.

Under AzureAdB2C

    "Instance": I assume this is the URL for our B2C AD Instance.
    "ClientId": Is this the client Id of the B2C app registration?
    "CallbackPath": Is this the URL of the App service?
    "Domain": Is this the B2C Domain name?
    "MetadataAddress": Could you confirm what this is and how to find it. I haven't used this before. 

Under GraphAPI
    "applicationId":  Is this the App id of the actual App Webservice?
    "tenantId": Is this the Id of the Tenancy the app is hosted in or our B2C id?
    "redirectUri": Is this the URL of the App service?

Any light you can shine on these would be appreciated. Cheers.

**Comment by stexncc** [comment]
Hi @BoozyDoo 

Thanks for the comments 

In regards to the AzureADB2C parameters please see below:

	   "Instance": "https://login.microsoftonline.com/tfp/", 
*^This is the standard Microsoft address*

     "ClientId":    Yes this is the application ID registered in B2C for the GoVote app 
    "MetadataAddress": "https://login.microsoftonline.com/<your Tenant ID>/v2.0/.well-known/openid-configuration?p=<Same as  SignUpSignInPolicyId entry>"

The GoVote application has the below permissions scope:
![GoVote App Registration Scope Permissions ](https://raw.githubusercontent.com/NCCOpenSource/GoVote/master/READMEImages/GOVoteAppRegScope.png)

These quick start links in regards to B2C and app registration may be useful:

[https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app)
[https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-dotnetcore-webapp/an-aspnet-core-web-app-with-azure-ad-b2c/](https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-dotnetcore-webapp/an-aspnet-core-web-app-with-azure-ad-b2c/)

GraphAPI  our settings :

      "GraphAPI": {  
        "applicationId":  is the application id for an application registered in  b2c tenant with read/write access AAD. We call ours graph API.
        "tenantId": "<tenant name >.onmicrosoft.com",
        "redirectUri": "http://www.google.com/home"

The permission scope for this are 
 ![B2C App Registration scope permissions to edit b2C AAD](https://raw.githubusercontent.com/NCCOpenSource/GoVote/master/READMEImages/B2CGraphAADAppRegScope.png)

We have noticed that login.microsoftonline.com is being deprecated so you may find these links also useful:
[https://azure.microsoft.com/en-gb/updates/b2c-deprecate-msol/](https://azure.microsoft.com/en-gb/updates/b2c-deprecate-msol/)
[https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview) 

We host the app in our standard azure AD tenant with  the Azure resources administered though our normal Azure AD, i.e. the web app resource is not in the Azure B2C space

Hope this helps 😊
